### ISSUE TITLE
Date field of ArcGIS REST service is not visible in Flamingo4 Viewer

### ISSUE THREAD

**Issue by NiekBouma** [B3Partners/flamingo#11]
A customer tries to show a date in the feature information of a map layer. The information comes from a ArcGIS REST service. The date field seems to be saved as a string and is not visible. All the other fields are shown,

URLs:
http://geoservices.zuid-holland.nl/arcgis/rest/services/Cultuur/Cultuurhistorie_Atlantikwall/MapServer/2

http://geoservices.zuid-holland.nl/arcgis/rest/services/Cultuur/Cultuurhistorie_Atlantikwall/MapServer/find?searchText=Voorne&contains=true&searchFields=Naam&sr=&layers=2&layerDefs=&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&dynamicLayers=&returnZ=false&returnM=false&gdbVersion=&f=html

[logbestand.txt](https://github.com/B3Partners/flamingo/files/182734/logbestand.txt)
![screenshot](https://cloud.githubusercontent.com/assets/14270448/13926709/e1414006-ef8d-11e5-9e4a-6cd7caafa17d.PNG)

**Comment by mprins** [comment]
ik sluit deze, afhandeling in flamingo-geocms/flamingo#558 (dat kan even duren, want afhankelijk van een geotools update)
