### ISSUE TITLE
In Internet Explorer (9 or 11) the bold statement <b>some text</b> does not work

### ISSUE THREAD

**Issue by NiekBouma** [B3Partners/flamingo#7]
In Internet Explorer (9 or 11) the bold statement <b>some text</b> does not work in the description field of a map layer. In Chrome it works fine.
![bold statement does not work in ie](https://cloud.githubusercontent.com/assets/14270448/11630994/47c22b32-9d00-11e5-99af-d8eaaa5b28b4.PNG)

**Comment by matthijsln** [comment]
Aub link naar app erbij posten

**Comment by NiekBouma** [comment]
Link to app: http://pzh.b3p.nl/viewer/app/Cultuur_historische_atlas/v4, map: 3a, part c. Landgoedbiotopen, Namen landgoedbiotopen.

**Comment by matthijsln** [comment]
Probleem speelt ook in Firefox. Oorzaak is font-weight: 300 regel in Ext, als je die regel uitzet in Firebug werkt het wel:

![image](https://cloud.githubusercontent.com/assets/1926261/11631945/deb4b1e6-9d04-11e5-8165-9851dcfb8bff.png)

Alternatief:
\<span style="font-weight: bold"\>Naam:\</span\>

@geertplaisier kan jij een structurele oplossing verzinnen?

**Comment by geertplaisier** [comment]
Fixed in master (c28aeecccdaa3a59a0d2f0a1d3d380434e730459)
